version: '3.6'

services:

  application:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - '80:80'

  cypress:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     - CYPRESS_TARGET_HOST=application